### ISSUE TITLE
java.lang.IndexOutOfBoundsException when referencing a non-existing member in json patch

### ISSUE THREAD

**Issue by noread** [javaee/jsonp#58]
When I attempt to perform a patch and reference a non-existing member I expect a JsonException to be thrown. However, I end up with an IndexOutOfBoundsException.

JSON data:
```
[
  {
    "name": "Jason Bourne",
    "profession": "Super agent",
    "phoneNumbers": [
      {
        "type": "home",
        "number": "123-456-789"
      },
      {
        "type": "work",
        "number": "123-555-555"
      }
    ]
  },
  {
    "name": "Jason Voorhees",
    "profession": "Maniac killer",
    "phoneNumbers": [
      {
        "type": "office",
        "number": "666-666-666"
      }
    ]
  }
]
```

Patch code:
```
private void jsonPatchDemo() {
        JsonReader reader = Json.createReader(Demo.class.getResourceAsStream("/jasons.json"));
        JsonArray jasons = reader.readArray();

        JsonPatch patch = Json.createPatchBuilder()
                .replace("/0/profession", "Maniac Killer")
                .replace("/2/profession", "Super Agent")
                .build();

        JsonArray result = patch.apply(jasons);
        System.out.println(result.toString());
    }
```

**Comment by m0mus** [comment]
This is a correct behaviour. Javadoc for apply method says:

> Throws:
> JsonException - if the supplied JSON Patch is malformed or if it contains references to non-existing members

**Comment by noread** [comment]
But it does not throw a JsonException.

This is the stacktrace I end up with:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at org.glassfish.json.JsonArrayBuilderImpl$JsonArrayImpl.get(JsonArrayBuilderImpl.java:485)
	at org.glassfish.json.JsonArrayBuilderImpl$JsonArrayImpl.get(JsonArrayBuilderImpl.java:384)
	at org.glassfish.json.JsonPointerImpl.getReferences(JsonPointerImpl.java:278)
	at org.glassfish.json.JsonPointerImpl.execute(JsonPointerImpl.java:233)
	at org.glassfish.json.JsonPointerImpl.replace(JsonPointerImpl.java:206)
	at org.glassfish.json.JsonPatchImpl.apply(JsonPatchImpl.java:171)
	at org.glassfish.json.JsonPatchImpl.apply(JsonPatchImpl.java:136)
	at javaee.json.demo.Demo.jsonPatchDemo(Demo.java:192)
	at javaee.json.demo.Demo.start(Demo.java:57)
	at javaee.json.demo.Demo.main(Demo.java:33)

Process finished with exit code 1
```

**Comment by m0mus** [comment]
@noread You are right. I am confirming the bug.
